Naive-bayes-classifire
simple implementation of song lyrics classifier using Naive Bayes classifier.

HOW TO USE IT:

There are some files used for different purpose.let's discuss about it.

*downloder.py* - (simple implimentation of WebScraping)

This file is used for download multiple lyrics from a [[http://www.metrolyrics.com][website]] called Metrolyrics. This website contain lots of lyrics with different category.we select [[http://www.metrolyrics.com/top-artists.html][artist]] from main page and go to artist page and select an artist. if you select an artist's name you can enter in to a new page. this page lists song's list of selected artist (Here this [[http://www.metrolyrics.com/justin-bieber-lyrics.html][page]] contain Justin Bieber's songs list).copy the page link.
Now run the downloder.py from your terminal and past this link when it ask for link
Now this program create a subfolder in training_data in the name of artist and download all the lyrics in to this folder and save in the name of songs name.

*requirements.txt*
If you want to run this scripts, first of all you must install all the requirements.

You can install all the requirements usig:

#+BEGIN_SRC

pip install -r requirements.txt

#+END_SRC

*Classifier.py*

- This is the core part of this program.
- Here it train the available data and predict test data belongs to which artist 

It displayes folowing:
- Table of prediction status.
- Accuracy of your system.
- Print no of worng and sucess predictions.

*Simple explanation about other files and folders.*

- pytest_data : demo data for pytest
- test_classifier.py : test file for classifier.py and status_test.py
